title: Smart City Toolkit
author:
  name: Smart City Toolkit.
#  email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Note and Disclaimer: This site was created to use our toolkit of information about smart cities.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  # social_links:
    # twitter: jekyllrb
    # github:  jekyll
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - transportation.md
 
sass:
  style: compressed

# Build settings
theme: minima

url: "https://cippic-ca.github.io/SmartCityToolkit/" # the base hostname & protocol for your site
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - jemoji


  